name: linter


on:

  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: make install

      - name: run lint
        run: npx eslint .

      - name: Test & publish code coverage
          uses: paambaati/codeclimate-action@v2.7.4
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          with:
            coverageCommand: make test-coverage
            debug: true
